version: 0.2

phases:
  install:
    commands:
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/handler"
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - echo GOPATH - $GOPATH
      - go get -v
      - go build -o klog main.go 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - klog
    - appspec.yml
  discard-paths: yes
