version: 0.2

phases:

  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - go get -verbose
      - go build -o klog main.go 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - klog
    - appspec.yml
  discard-paths: yes
